import { Component, OnInit } from '@angular/core';
import { take } from 'rxjs';
// import { WeatherForecast } from '../models/autogenerated/weatherForecast';
import { WindService } from '../../services/wind.service';

@Component({
  selector: 'app-fetch-data',
  templateUrl: './fetch-data.component.html',
})
export class FetchDataComponent implements OnInit {
  public forecasts: [] = [];

  constructor(private windService: WindService) {}
  ngOnInit(): void {
    this.windService
      .getWind()
      .pipe(take(1))
      .subscribe((data) => {
        console.log(data);
      });
  }
}
