import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormArray, FormControl, FormGroup, Validators } from '@angular/forms';
import {
  Icon,
  LeafletMouseEvent,
  Map,
  MapOptions,
  Marker,
  icon,
  latLng,
  marker,
  tileLayer,
} from 'leaflet';
import { Subject, takeUntil } from 'rxjs';
import {
  IFormWindCalculatorBindingModel,
  WindCalculatorBindingModel,
} from 'src/app/models/autogenerated/windCalculatorBindingModel';
import { IFormWindSpeedPowerPairBindingModel } from 'src/app/models/autogenerated/windSpeedPowerPairBindingModel';
import { WindService } from 'src/app/services/wind.service';

@Component({
  selector: 'app-wind-calculator',
  templateUrl: './wind-calculator.component.html',
  styleUrls: ['./wind-calculator.component.scss'],
})
export class WindCalculatorComponent implements OnInit, OnDestroy {
  private readonly latDefault = 45.815399;
  private readonly lngDefault = 15.966568;
  private map: Map;
  private destroy$: Subject<void> = new Subject<void>();
  public form: FormGroup<IFormWindCalculatorBindingModel>;

  public pickMarker: Marker = marker([this.latDefault, this.lngDefault], {
    icon: icon({
      ...Icon.Default.prototype.options,
      iconUrl: 'assets/images/vendors/leaflet/marker-icon.png',
      iconRetinaUrl: 'assets/images/vendors/leaflet/marker-icon-2x.png',
      shadowUrl: 'assets/images/vendors/leaflet/marker-shadow.png',
    }),
  });
  public options: MapOptions = {
    layers: [
      tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        minZoom: 1,
        attribution: '...',
      }),
    ],
    zoom: 7,
    center: latLng(this.latDefault, this.lngDefault),
  };

  constructor(private windService: WindService) {}

  ngOnInit(): void {
    this.initForm();
    this.subToWindClassChange();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private initForm() {
    this.form = new FormGroup<IFormWindCalculatorBindingModel>({
      latitude: new FormControl(this.latDefault, Validators.required),
      longitude: new FormControl(this.lngDefault, Validators.required),
      windClassWidth: new FormControl(2, Validators.required),
      windPowerPairs: new FormArray([]),
    });

    this.addNewPair();
  }

  private subToWindClassChange(): void {
    const windClassControl = this.form.controls.windClassWidth;
    windClassControl.valueChanges
      .pipe(takeUntil(this.destroy$))
      .subscribe((val) => {
        this.updateWindSpeeds();
      });
  }

  private updateWindSpeeds(): void {
    const windClassSpeed = this.form.controls.windClassWidth.value;
    this.form.controls.windPowerPairs.controls.forEach((ctrl, i) => {
      ctrl.controls.windSpeed.setValue(i * windClassSpeed);
    });
  }

  public addNewPair(): void {
    let pairsControl = this.form.controls.windPowerPairs;
    if (pairsControl.invalid) {
      pairsControl.markAllAsTouched();
    }

    const newPair = new FormGroup<IFormWindSpeedPowerPairBindingModel>({
      windSpeed: new FormControl(
        { value: 0, disabled: true },
        Validators.required
      ),
      power: new FormControl(0, Validators.required),
    });
    pairsControl.push(newPair);

    this.updateWindSpeeds();
  }

  public removeLastPair(): void {
    let pairsControl = this.form.controls.windPowerPairs;

    if (pairsControl.length == 1) {
      return;
    }
    pairsControl.controls.pop();
  }

  public submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
    }
    const model: WindCalculatorBindingModel = this.form.getRawValue();

    this.windService.calculateWindEnergy(model);
  }

  public updatePosition(e: LeafletMouseEvent): void {
    this.form.controls.latitude.setValue(+e.latlng.lat.toFixed(6));
    this.form.controls.longitude.setValue(+e.latlng.lng.toFixed(6));

    this.pickMarker = marker([e.latlng.lat, e.latlng.lng]);
  }

  public onMapReady(map: Map) {
    this.map = map;
    // Do stuff with map
  }
}
