import { HttpClient } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { Observable, catchError, of } from 'rxjs';
import { WindCalculatorBindingModel } from '../models/autogenerated/windCalculatorBindingModel';
import { WindDailyEnergyDto } from '../models/autogenerated/windDailyEnergyDto';

@Injectable({
  providedIn: 'root',
})
export class WindService {
  private windApi: string;

  constructor(
    private http: HttpClient,
    @Inject('BASE_URL') private baseUrl: string
  ) {
    this.windApi = this.baseUrl + '/wind';
  }

  public getWind(): Observable<any[]> {
    return this.http.get<any[]>(this.windApi).pipe(
      catchError((err) => {
        return of([]);
      })
    );
  }

  public calculateWindEnergy(
    model: WindCalculatorBindingModel
  ): Observable<WindDailyEnergyDto> {
    return this.http.post<WindDailyEnergyDto>(this.windApi, model).pipe(
      catchError((err) => {
        return of(null);
      })
    );
  }
}
